export const colleges: string[] = [
  "Alabama",
  "Auburn",
  "Clemson",
  "Florida",
  "Florida State",
  "Georgia",
  "LSU",
  "Michigan",
  "Notre Dame",
  "Ohio State",
  "Oklahoma",
  "Oregon",
  "Penn State",
  "Texas",
  "USC",
  "Miami",
  "Tennessee",
  "Wisconsin",
  "Stanford",
  "UCLA",
  "Washington",
  "Texas A&M",
  "Nebraska",
  "Iowa",
  "Michigan State",
  "Oklahoma State",
  "Pittsburgh",
  "North Carolina",
  "Virginia Tech",
  "Georgia Tech",
  "South Carolina",
  "Arkansas",
  "Mississippi State",
  "Ole Miss",
  "Kentucky",
  "Vanderbilt",
  "Missouri",
  "California",
  "Arizona",
  "Arizona State",
  "Colorado",
  "Utah",
  "Oregon State",
  "Washington State",
  "Boise State",
  "BYU",
  "TCU",
  "Houston",
  "Cincinnati",
  "Louisville",
  "West Virginia",
  "Syracuse",
  "Boston College",
  "Maryland",
  "Rutgers",
  "Illinois",
  "Indiana",
  "Iowa State",
  "Kansas",
  "Kansas State",
  "Minnesota",
  "Northwestern",
  "Purdue",
  "Duke",
  "NC State",
  "Wake Forest",
  "Virginia",
  "Miami (OH)",
  "Ohio",
  "Toledo",
  "Central Michigan",
  "Western Michigan",
  "Eastern Michigan",
  "Northern Illinois",
  "Bowling Green",
  "Kent State",
  "Akron",
  "Buffalo",
  "Temple",
  "Memphis",
  "Tulane",
  "Tulsa",
  "SMU",
  "UCF",
  "USF",
  "East Carolina",
  "Navy",
  "Army",
  "Air Force",
  "UTEP",
  "UTSA",
  "North Texas",
  "Rice",
  "UAB",
  "Southern Miss",
  "Marshall",
  "Florida Atlantic",
  "Florida International",
  "Charlotte",
  "Old Dominion",
  "Western Kentucky",
  "Middle Tennessee",
  "Louisiana Tech",
  "Louisiana",
  "ULM",
  "Arkansas State",
  "Troy",
  "South Alabama",
  "Georgia Southern",
  "Georgia State",
  "Coastal Carolina",
  "Appalachian State",
  "Liberty",
  "New Mexico",
  "New Mexico State",
  "UNLV",
  "Nevada",
  "Fresno State",
  "San Diego State",
  "San Jose State",
  "Hawaii",
  "Wyoming",
  "Colorado State",
  "Utah State",
  "Idaho",
  "Montana",
  "Montana State",
  "Eastern Washington",
  "Portland State",
  "Sacramento State",
  "Cal Poly",
  "UC Davis",
  "Weber State",
  "Northern Arizona",
  "Southern Utah",
  "Idaho State",
  "North Dakota State",
  "South Dakota State",
  "North Dakota",
  "South Dakota",
  "Northern Iowa",
  "Illinois State",
  "Western Illinois",
  "Southern Illinois",
  "Missouri State",
  "Youngstown State",
  "Indiana State"
]; 